// @generated — DO NOT EDIT. Regenerate with `npm run errors:catalog`.
// Source of truth: docs/ERROR-HANDLING.md §2 (87 codes). Sync-enforced by
// scripts/docs-verify.mjs (7e). Consumed by the S-076 in-app Error reference (§3 rule 5).

/** One §2 catalog row: the wire contract every screen renders (B12). */
export interface ErrorCatalogEntry {
  code: string;
  /** Short machine cause from the doc table (not user-facing copy). */
  cause: string;
  /** The exact catalog userMessage — what a user should read in-app. */
  userMessage: string;
  httpStatus: number;
  retryable: boolean;
}

export const ERROR_CATALOG: readonly ErrorCatalogEntry[] = [
  {
    code: "AUTH_PIN_INVALID",
    cause: "pin verification failed",
    userMessage: "Incorrect PIN.",
    httpStatus: 401,
    retryable: false,
  },
  {
    code: "AUTH_LOCKED",
    cause: "too many failed attempts",
    userMessage: "Too many attempts. Try again in {countdown}s.",
    httpStatus: 423,
    retryable: true,
  },
  {
    code: "SESSION_LOCKED",
    cause: "session expired",
    userMessage: "Session locked. Unlock to continue.",
    httpStatus: 401,
    retryable: false,
  },
  {
    code: "PIN_POLICY_WEAK",
    cause: "policy not met",
    userMessage: "PIN must be ≥8 characters with letters and digits.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "LICENSE_INVALID_SIGNATURE",
    cause: "ed25519 verify failed",
    userMessage: "This license key is invalid. Contact your vendor.",
    httpStatus: 403,
    retryable: false,
  },
  {
    code: "LICENSE_EXPIRED",
    cause: "license past expiry",
    userMessage: "License expired. The Company is read-only. Activate to continue.",
    httpStatus: 403,
    retryable: false,
  },
  {
    code: "STORAGE_FILE_EXISTS",
    cause: "path exists",
    userMessage: "A file already exists at that location. Choose another name.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "STORAGE_FILE_CORRUPT",
    cause: "integrity check failed",
    userMessage:
      "This Company file could not be verified. Restore from Backup? (pre-restore snapshot will be taken)",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "STORAGE_DECRYPT_FAILED",
    cause: "key mismatch",
    userMessage: "The Company file cannot be decrypted with this PIN.",
    httpStatus: 401,
    retryable: false,
  },
  {
    code: "IMPORT_FILE_UNREADABLE",
    cause: "parse failed",
    userMessage:
      "This file could not be read. Export it again as .xlsx or .csv without a password.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "IMPORT_FILE_LOCKED",
    cause: "encrypted workbook",
    userMessage: "This file is password-protected. Remove protection and export again.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "ENCODING_UNSUPPORTED",
    cause: "unknown charset",
    userMessage: "Encoding not detected. Choose UTF-8 or Latin-1 (preview) and continue.",
    httpStatus: 422,
    retryable: true,
  },
  {
    code: "BACKUP_DISK_FULL",
    cause: "disk full",
    userMessage: "Backup failed — no space. Your Company data is unchanged.",
    httpStatus: 507,
    retryable: true,
  },
  {
    code: "BACKUP_PASSPHRASE_INVALID",
    cause: "wrong passphrase",
    userMessage: "Incorrect backup passphrase.",
    httpStatus: 401,
    retryable: false,
  },
  {
    code: "BACKUP_IO_ERROR",
    cause: "io failed",
    userMessage: "Backup could not be written. Check permissions and retry.",
    httpStatus: 500,
    retryable: true,
  },
  {
    code: "IMPORT_TIE_OUT_FAILED",
    cause: "debits != credits",
    userMessage: "Import blocked: debits {d} vs credits {c}. Review flagged rows below.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "IMPORT_BATCH_HASH_EXISTS",
    cause: "duplicate source",
    userMessage:
      "This exact file was already imported (batch {id}). Re-import? This will create a new batch — confirm: duplicate rows are excluded automatically.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "IMPORT_PARSE_EXPIRED",
    cause: "session expired",
    userMessage: "This parse session expired. Re-run the import.",
    httpStatus: 410,
    retryable: true,
  },
  {
    code: "MAP_ACCOUNT_AMBIGUOUS",
    cause: "account not unique",
    userMessage: "Account code maps to multiple Accounts ({list}). Confirm the intended Account.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "MAP_TARGET_INVALID",
    cause: "mapping target invalid",
    userMessage: "This column cannot map to that field. Choose a supported target.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "UNIT_PERIOD_MISMATCH",
    cause: "driver/week period",
    userMessage: "Driver data is weekly but the calendar is monthly. Aggregate (sum) or reject?",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "OPENING_ALREADY_SET",
    cause: "opening exists",
    userMessage:
      "Opening balances already exist for this period. Use a new Actuals batch to adjust.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "CAL_53WEEK_CONFLICT",
    cause: "rule mismatch",
    userMessage:
      "The 53rd week rule conflicts with your FY start. Choose NRF (4+ days) or full-week rule.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "CAL_TRANSIT_AMBIGUOUS",
    cause: "partial mapping",
    userMessage: "BU period {p} spans two Group periods. Map both date ranges to proceed.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "CAL_PERIOD_MAPPING_CONFLICT",
    cause: "overlap",
    userMessage:
      "Two BUs map the same Group period with different calendars — confirm the Transit Map.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "COA_DUPLICATE_CODE",
    cause: "code exists",
    userMessage: "Account code {code} already exists in this scope.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "COA_REFERENCED",
    cause: "in use",
    userMessage: "Account is used by {n} lines/batches. Merge or remap instead of deleting.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "COA_TYPE_MISMATCH",
    cause: "type differs",
    userMessage: "Cannot merge: account types differ (Revenue vs COGS).",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "ARCHIVE_IN_USE_REF",
    cause: "reference",
    userMessage: "Sandbox references the archived year. Use a Year copy before cloning.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "ARCHIVE_IN_USE",
    cause: "in use",
    userMessage:
      "This Fiscal Year still has data attached (models, drivers, GL lines, or mappings). Remove or re-point them first.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "MODEL_CELL_LOCKED",
    cause: "scenario locked",
    userMessage: "This scenario is locked. Create a Version to edit it.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "MODEL_SIZE_LIMIT",
    cause: "exceeds 1M cells",
    userMessage: "This Model exceeds the 1,000,000-cell limit. Split it or reduce the horizon.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "SHEET_NAME_DUP",
    cause: "name exists",
    userMessage: "A Sheet with this name already exists.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "FORMULA_CYCLE",
    cause: "cycle detected",
    userMessage: "Formula cycle detected: path {path} — shown as #CYCLE!. Fix the reference.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "REFERENCE_BROKEN",
    cause: "broken ref",
    userMessage: "Reference to {cell} is broken (sheet renamed/deleted). Repair or remove.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "DRIVER_OUT_OF_BOUNDS",
    cause: "driver beyond bounds",
    userMessage:
      "Driver value {v} is outside its bounds [{low}, {high}]. Update bounds (audited) or fix the value.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "DRIVER_FEED_MISSING",
    cause: "no source",
    userMessage: "Driver has no data and no feed source. Import, collect, or set a static value.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "HARDCODED_ASSUMPTION",
    cause: "value not reference",
    userMessage:
      "This cell uses a hardcoded value instead of an Assumption Register reference. Convert (recommended) or waive with a reason.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "VALUE_INVALID",
    cause: "parse/type",
    userMessage: "Value is not valid for this cell ({type}).",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "GOAL_SEEK_NO_CONVERGE",
    cause: "iterations exhausted",
    userMessage:
      "Goal Seek did not converge in 100 iterations. Last value {v}, target {t}. Adjust bounds.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "SENSITIVITY_OUT_OF_BOUNDS",
    cause: "outside bounds",
    userMessage: "Sensitivity range exceeds the Assumption bounds. Adjust bounds or range.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "SCENARIO_NAME_DUP",
    cause: "name exists",
    userMessage: "A Scenario with this name already exists.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "SCENARIO_LOCK_CONFLICT",
    cause: "state conflict",
    userMessage: "This Scenario is already in {state} — cannot transition.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "COMPARE_INCOMPATIBLE",
    cause: "different model",
    userMessage: "Cannot compare: Models/COAs differ. Select two Scenarios of the same Model.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "ASSUMPTION_IN_USE_LOCKED",
    cause: "locked",
    userMessage: "Assumption is used by a Locked Baseline. Create a new Version to change.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "SPREAD_WEIGHTS_INVALID",
    cause: "sum != 100",
    userMessage: "Seasonality weights total {sum}% — normalize to 100% or fix.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "FORMULA_UNSUPPORTED_FUNCTION",
    cause: "function not in set",
    userMessage:
      "Function {fn} is not in the supported set (see FORMULA-ENGINE-SPEC.md). Replace it or file a V2 request.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "HC_DATE_INVALID",
    cause: "schedule date invalid",
    userMessage: "A hire or termination date is outside the active fiscal calendar.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "HC_OVERLAP",
    cause: "schedule rows overlap",
    userMessage: "Two rows for the same role and cost center overlap in a fiscal period.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "PACK_SCHEMA_INVALID",
    cause: "validation failed",
    userMessage: "Industry Pack failed validation at {path}. Retry or use the bundled Core Pack.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "PACK_VERSION_EXISTS",
    cause: "version installed",
    userMessage: "Pack version {v} is already installed.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "PACK_IN_USE_LOCKED",
    cause: "locked reference",
    userMessage: "This Pack version is used by a Locked Baseline. Clone the Pack before editing.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "PACK_UPDATE_AVAILABLE",
    cause: "new pack version",
    userMessage:
      "A newer version of this Industry Pack is available ({old} → {new}) for new Models.",
    httpStatus: 200,
    retryable: false,
  },
  {
    code: "CYCLE_NAME_DUP",
    cause: "name exists",
    userMessage: "A planning cycle with this name already exists.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "CYCLE_TASK_BLOCKED",
    cause: "dependency",
    userMessage: "This task is blocked by unfinished tasks: {list}.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "COLLECTION_CONFLICT",
    cause: "conflict",
    userMessage:
      "This Driver value was changed by more than one contributor. Resolve the conflict (choose or average) — never merged silently.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "COLLECTION_STRUCTURE_CHANGED",
    cause: "template drift",
    userMessage:
      "The returned sheet differs from the exported template (rows/columns changed). Review the diff before merging.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "CAPEX_IN_SERVICE_INVALID",
    cause: "date order",
    userMessage: "Depreciation cannot start before the capital project's in-service date.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "PRODUCTION_CAPACITY",
    cause: "over capacity",
    userMessage:
      "Production exceeds available capacity ({units} > {capacity}). Raise capacity (audited) or reduce the plan.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "REVREC_COST_ESTIMATE_INVALID",
    cause: "zero estimate",
    userMessage: "Revenue recognition needs a non-zero total cost estimate (over-time method).",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "COMPANY_IN_USE_RECENT",
    cause: "retention",
    userMessage:
      "This Company was used less than {days} days ago. Delete it or wait — recent Companies can't be deleted.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "BASELINE_REPLACE_REASON_REQUIRED",
    cause: "governance",
    userMessage: "Replacing the baseline requires a written reason.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "MODEL_YEAR_EXISTS",
    cause: "duplicate",
    userMessage: "A Model already exists for this fiscal year.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "SOURCE_BOOTSTRAP_EMPTY",
    cause: "empty source",
    userMessage: "The source year has no values to bootstrap.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "PACK_NO_COMMENTARY",
    cause: "narrative gate",
    userMessage:
      "Variance commentary is required before this Board Pack can be generated. Add Reason Codes/narrative in S-054.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "SRC_MISMATCH_UNRESOLVED",
    cause: "diff open",
    userMessage: "Sources differ on {n} accounts. Resolve or mark authoritative before closing.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "STATEMENT_TIE_OUT_FAILED",
    cause: "tie out fail",
    userMessage: "Statement does not tie ({detail}). Export blocked — fix {findings} first.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "STATEMENT_SOURCE_MIXED",
    cause: "calendar/currency",
    userMessage:
      "Period/currency mix in scope is not comparable. Align scope or use Group translation.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "PERIOD_NOT_FOUND",
    cause: "period missing",
    userMessage: "Period not found in this calendar.",
    httpStatus: 404,
    retryable: false,
  },
  {
    code: "VARIANCE_NO_ATTRIBUTION_DATA",
    cause: "no driver data",
    userMessage:
      "Attribution unavailable for these lines — no unit/driver data. Show $ variance only.",
    httpStatus: 200,
    retryable: false,
  },
  {
    code: "VARIANCE_SOURCE_MIXED",
    cause: "mixed states",
    userMessage: "Selected periods mix Actual and Forecast — enable HYBRID label to view.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "FVA_RESTATEMENT_FLAG",
    cause: "restated",
    userMessage: "Actuals were restated for these periods — FVA recomputed; versions unchanged.",
    httpStatus: 200,
    retryable: true,
  },
  {
    code: "KPI_FORMULA_INVALID",
    cause: "formula bad",
    userMessage: "KPI formula invalid: {detail}.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "KPI_DIV_ZERO",
    cause: "div by zero",
    userMessage: "KPI divides by zero — shows n/a. Add a denominator source or guard.",
    httpStatus: 200,
    retryable: false,
  },
  {
    code: "LAYOUT_REFERENCE_BROKEN",
    cause: "broken refs",
    userMessage: "Layout references {n} missing lines. Auto-remap or fix.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "LAYOUT_INVALID",
    cause: "schema bad",
    userMessage: "Layout schema invalid at {path}.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "ALERT_RULE_INVALID",
    cause: "rule bad",
    userMessage: "Alert rule invalid: {detail}",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "HEALTH_CHECK_BLOCKED",
    cause: "findings",
    userMessage: "Export blocked by {n} Health Check findings. Fix or waive (reason required).",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "HEALTH_WAIVER_REASON_REQUIRED",
    cause: "no reason",
    userMessage: "A waiver reason is required.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "AUDIT_CHAIN_BREAK",
    cause: "hash mismatch",
    userMessage: "Audit integrity check failed. Restore from the last verified Snapshot?",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "BATCH_ALREADY_ROLLED_BACK",
    cause: "state",
    userMessage: "This batch was already rolled back.",
    httpStatus: 409,
    retryable: false,
  },
  {
    code: "IC_UNMATCHED",
    cause: "no counterpart",
    userMessage:
      "Intercompany line {id} has no matching counterpart. Pair or classify as external.",
    httpStatus: 422,
    retryable: false,
  },
  {
    code: "SEGMENT_TRANSLATION_PENDING",
    cause: "rates missing",
    userMessage: "FX rates missing for {periods}. Add rates or set policy.",
    httpStatus: 409,
    retryable: true,
  },
  {
    code: "SETTINGS_SAVE_FAILED",
    cause: "write failed",
    userMessage: "Settings could not be saved. Retry.",
    httpStatus: 500,
    retryable: true,
  },
  {
    code: "HELP_TOPIC_MISSING",
    cause: "no topic",
    userMessage: "No help topic for '{x}' — try search.",
    httpStatus: 404,
    retryable: false,
  },
  {
    code: "EXPORT_FORMULA_INJECTION_GUARD",
    cause: "guard",
    userMessage:
      "Text cells starting with '=' were quoted (formula-injection protection) — review before export.",
    httpStatus: 200,
    retryable: false,
  },
  {
    code: "INTERNAL",
    cause: "unexpected",
    userMessage:
      "Something went wrong. Diagnostics were captured — retry or export Local Diagnostics.",
    httpStatus: 500,
    retryable: true,
  },
] as const;
